### ISSUE TITLE
per Daemon configuration (avoid singleton config)

### ISSUE THREAD

**Issue by carandraug** [irmen/Pyro5#3]
We have a program that starts multiple Pyro daemons and we would like to have different configurations for each daemon. This was not possible on Pyro4 and I was hoping it would be a thing for Pyro5 (seems not).

The way I would envision this is to have a new `config`argument to the `Daemon` constructor which would default to a `configuration.Configuration` instance. It seems that in `Pyro5` there is not longer a `Configuration` class like there was in Pyro4 so not sure how to go about doing that.

Not sure how to go about this and if this could be fitted in the vision for Pyro5.

**Comment by irmen** [comment]
It is a good idea and I will certainly give this some thought. Perhaps the config class should be brought back.

**Comment by irmen** [comment]
@carandraug by the way, can you not simple run multiple daemons with their own config, in separate processes?

**Comment by catchthemonster** [comment]
So I have an issue that relates to this irmen.
I want to run a message bus as one daemon, IP is public and another daemon that deals with moving objects across the network. Multiplex daemon would join both. Problem is that for some reason in Pyro5 daemons can't run on the same IP address different port. Why is that?

**Comment by irmen** [comment]
This is not true? I ran many deamons on my single IP system. There are even a bunch of examples included in the repo that show how to do this including a dispatcher even.  What exactly are you trying to do? @catchthemonster

**Comment by catchthemonster** [comment]
ok, got it

**Comment by carandraug** [comment]
> @carandraug by the way, can you not simply run multiple daemons with their own config, in separate processes?

Yes, this is what we've been doing on Pyro4 but multiprocessing in Python is now without its own bunch of caveats. I thought it would be cleaner to have each daemon with its own configuration since I see no reason why multiple daemon instances would want to share configuration.

**Comment by catchthemonster** [comment]
@carandraug, I agree! 
I thin that is the reason why two daemons I am using (one is 2-way ssl on public IP) and one is localhost messageBus, are not working correctly. Yes I mixed daemon configurations, but not MP, just separate implementations for both daemons withing one process. everything bootstraps correctly and I have one master daemon corralling two daemons which are using multiples servers. However, if I publish message on the localhost, threading will not save it correctly to RAM. I corrected that one but still I have problem running subscriber and collecting messages. So at the end I am giving up being fancy and I will instead of threaded message bus on the localhost just have simple daemon with exposed method that can serialize a message. I do agree with you that daemons should have separate daemon configurations thus exist and separate name spaces in virtual machine or mp's if you wish to go that way. That would allow Python frameworks to inject Pyro left and right into variety of scenarios.
