### ISSUE TITLE
Pyro5 not automatically exposing base classes

### ISSUE THREAD

**Issue by pevogam** [irmen/Pyro5#96]
If I expose a class A that inherits from a class B, is there any reason why the methods of class B are not automatically available and I have to expose class B separately? In some cases I have to walk up long chains of inheritance to expose each class separately despite the usual expectation that an inheriting class must simply extend the public methods of its base class. Am I missing something here?

**Comment by irmen** [comment]
Pyro5 takes the secure by default route - it doesn't expose more of the class remotely than precisely what you asked for.   The @expose is on the class you put it on and nothing more.
(Actually the manual contains the advice to not even do that, but explicitly single out the methods you want to expose and only put @expose on those)

Exposing a whole inheritance tree is against that spirit of thought - Pyro5 should never expose methods of whatever the inheritance tree might be unless specifically told to do so.  If someone were to refactor the program and change one of the base classes or the whole inheritance tree, all kinds of internal methods could end up being remotely accessible otherwise.

Now - re reading the documentation, I agree that it may not be clear enough about this aspect of the behavior. I'll try to add some more clarifications to the text in https://pyro5.readthedocs.io/en/latest/servercode.html#creating-a-pyro-class-and-exposing-its-methods-and-properties
