### ISSUE TITLE
Reasons for removing the async proxy code

### ISSUE THREAD

**Issue by pevogam** [irmen/Pyro5#98]
Hi, we were almost done migrating our use cases from Pyro4 to Pyro5 when I noticed this
```python
def asyncproxy(*args, **kwargs):
    raise NotImplementedError("async proxy is no longer available in Pyro5")
```
I traced back the history to read some motivation on why this was removed in the git history but all I could find is
```
Author: Irmen de Jong <irmen@razorvine.net>  2017-03-12 15:41:32

    removed all async proxy code
```
and
```
Author: Irmen de Jong <irmen@razorvine.net>  2019-04-16 23:30:42

    async proxy isn't going to come back any time soon
```
without any clue why a piece of code which was already existing and extending the current functionality is gone. The modified TODO had "create an alternative for Pyro4's async proxy, and fix the examples that use it: distributed-computing2, distributed-mandelbrot" but no clear direction why an alternative was needed on the first place. The [Upgrading from Pyro4](https://pyro5.readthedocs.io/en/latest/intro.html#upgrading-from-pyro4) section also doesn't mention anything.

**Comment by irmen** [comment]
The upgrading from Pyro4 does mention it though:

* async proxy removed (may come back but probably not directly integrated into the Proxy class)

It says "may come back" but that won't happen anymore.

Now, WHY it was removed I don't really remember. It has been 5 years since.  I vaguely recall it not being compatible with all the new Python async stuff -- better leave it to the application code to choose in what way it wants or needs to implement asynchronicity, than enforcing a method in the library that doesn't integrate.

**Comment by irmen** [comment]
I think the problem was that Pyro4 enforced the use of background threads to achieve the "async" calls.  And that the choice to do that and how to do that is better left to the application code.

**Comment by pevogam** [comment]
Ok, I guess then this issue could be considered a way to document these thoughts and the actual motivation behind the version history.
